<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hh_theme_default"
 *
 * Auto generated by Extension Builder 2017-02-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['hh_theme_default'] = [
    'title' => 'Hauer-Heinrich - Theme - Default',
    'description' => 'Distribution theme: Anpassbar im Backend im Konstanten Editor.',
    'category' => 'distribution',
    'author' => 'Christian Hackl',
    'author_email' => 'web@hauer-heinrich.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.9.99',
            'fluid_styled_content' => '9.5.0-10.9.9',
            'hh_seo' => '',
            'hh_slider' => ''
        ],
        'conflicts' => [
        ],
        'suggests' => [
            // 'min' => ''
        ],
    ],
    'autoload' => [
        'psr-4' => [
            'HauerHeinrich\\HhThemeDefault\\' => 'Classes'
        ],
    ],
];
