rootPageId: 1
base: 'https://www.{{EXTENSION_DOMAIN_NAME}}.{{EXTENSION_DOMAIN_TLD}}'
baseVariants:
  -
    base: 'http://preview.{{EXTENSION_DOMAIN_NAME}}.{{EXTENSION_DOMAIN_TLD}}'
    condition: 'applicationContext == "Development/Server"'
  -
    base: 'http://www.{{EXTENSION_DOMAIN_NAME}}.localhost'
    condition: 'applicationContext == "Development"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: '0'
    base: /
    typo3Language: de
    locale: de_DE.UTF-8 # https://gist.github.com/jasef/337431c43c3addb2cbd5eb215b376179
    iso-639-1: de # https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
    navigationTitle: DE
    hreflang: de
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: de
  -
    title: English
    enabled: true
    languageId: '1'
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: EN
    hreflang: en
    direction: ltr
    fallbackType: free
    fallbacks: '0'
    flag: en-us-gb
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=9' # uid = page UID from the BE page tree
  -
    errorCode: '503'
    errorHandler: Page
    errorContentSource: 't3://page?uid=10' # uid = page UID from the BE page tree
### Import default Robots.txt
imports:
  - { resource: "EXT:{{EXTENSION_KEY}}/Configuration/Typo3/dummy_files/dummy_site/robots.yaml" }
  - { resource: "EXT:{{EXTENSION_KEY}}/Configuration/Typo3/dummy_files/dummy_site/humans.yaml" }
  - { resource: "EXT:{{EXTENSION_KEY}}/Configuration/Typo3/dummy_files/dummy_site/extensions/news.yaml" }
  - { resource: "EXT:{{EXTENSION_KEY}}/Configuration/Typo3/dummy_files/dummy_site/extensions/tt_address.yaml" }
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
