
INSERT INTO tx_news_domain_model_news (title, teaser, tstamp, crdate, bodytext, pid) VALUES
('Produkt Launch 2025', 'Neues Produkt wird bald auf den Markt kommen.', 1735747200, 1735747200, 'Wir freuen uns, die Einführung unseres neuesten Produkts bekannt zu geben. Es wird bahnbrechende Funktionen und eine verbesserte Benutzererfahrung bieten. Bleiben Sie dran für weitere Details!', 13),
('Sommer Sale 2025', 'Große Rabatte in diesem Sommer!', 1741276800, 1741276800, 'Unser Sommer Sale beginnt bald. Erhalten Sie bis zu 50% Rabatt auf viele Artikel. Verpassen Sie nicht diese einmalige Gelegenheit!', 13),
('Jahresbericht 2024', 'Wichtige Informationen zum Geschäftsjahr 2024', 1730534400, 1730534400, 'Der Jahresbericht 2024 wurde veröffentlicht. Schauen Sie sich die wichtigsten Erkenntnisse und Zahlen des letzten Jahres an. Unser Unternehmen hat beeindruckende Ergebnisse erzielt.', 13),
('Technologie Messe 2025', 'Besuchen Sie uns auf der Tech Expo!', 1745097600, 1745097600, 'Die Technologie Messe 2025 wird bald stattfinden, und wir sind dabei! Erfahren Sie mehr über die neuesten Innovationen und Entwicklungen in der Branche.', 13),
('Kundenfeedback Umfrage', 'Helfen Sie uns, uns zu verbessern.', 1733635200, 1733635200, 'Ihre Meinung zählt! Bitte nehmen Sie an unserer Kundenfeedback-Umfrage teil und helfen Sie uns, unseren Service zu verbessern. Ihr Feedback ist uns wichtig.', 13),
('Neuer Blogbeitrag: SEO-Tipps', 'Erfahren Sie, wie Sie Ihre Webseite optimieren.', 1735632000, 1735632000, 'In unserem neuesten Blogbeitrag teilen wir wertvolle SEO-Tipps, die Ihnen helfen, Ihre Website in den Suchmaschinen zu verbessern und mehr Traffic zu generieren.', 13),
('Produktbewertungen 2025', 'Erfahrungsberichte und Bewertungen von Kunden', 1740624000, 1740624000, 'Lesen Sie die neuesten Produktbewertungen und Erfahrungsberichte von zufriedenen Kunden. Finden Sie heraus, warum unser Produkt so beliebt ist!', 13),
('Winterreise Angebote', 'Günstige Reisen für den Winter 2025', 1761465600, 1761465600, 'Entdecken Sie unsere exklusiven Winterreiseangebote für das Jahr 2025. Günstige Flüge und Hotelangebote warten auf Sie. Planen Sie noch heute Ihre Winterreise!', 13),
('Webinar: Digitales Marketing', 'Nehmen Sie an unserem kostenlosen Webinar teil', 1745952000, 1745952000, 'Melden Sie sich für unser kostenloses Webinar zum Thema digitales Marketing an. Erfahren Sie, wie Sie Ihre Online-Präsenz verbessern und erfolgreich vermarkten können.', 13),
('Team Event 2025', 'Unser jährliches Teamevent steht bevor!', 1742092800, 1742092800, 'Unser Team-Event für 2025 findet bald statt. Sehen Sie, wie wir uns gegenseitig unterstützen und feiern, was wir gemeinsam erreicht haben.', 13),
('Karrierechance: Marketing Manager', 'Werden Sie Teil unseres Teams!', 1739990400, 1739990400, 'Wir suchen einen talentierten Marketing Manager. Wenn Sie eine Leidenschaft für Marketing haben und gerne im Team arbeiten, freuen wir uns auf Ihre Bewerbung.', 13),
('Saisonale Produktneuheiten', 'Neuheiten für den Frühling 2025', 1732435200, 1732435200, 'Entdecken Sie die neuesten saisonalen Produktneuheiten für den Frühling 2025. Von frischen Designs bis zu praktischen Innovationen – wir haben für jeden etwas dabei.', 13);
