rootPageId: 1
base: 'https://www.test_theme_default.com'
baseVariants:
  -
    base: 'https://preview.test_theme_default.com'
    condition: 'applicationContext == "Development/Server"'
  -
    base: 'http://www.test_theme_default.localhost'
    condition: 'applicationContext == "Development"'

languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de # https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
    navigationTitle: DE
    hreflang: de
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: de

errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=9' # uid = page UID from the BE page tree
  -
    errorCode: '503'
    errorHandler: Page
    errorContentSource: 't3://page?uid=10' # uid = page UID from the BE page tree

### Import default Robots.txt
imports:
  - { resource: "EXT:{{EXTENSION_KEY}}/sites/site_default/robots.yaml" }
  - { resource: "EXT:{{EXTENSION_KEY}}/sites/site_default/humans.yaml" }
  - { resource: "EXT:{{EXTENSION_KEY}}/sites/site_default/extensions/news.yaml" }
  - { resource: "EXT:{{EXTENSION_KEY}}/sites/site_default/extensions/tt_address.yaml" }

routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
