rootPageId: 1
base: 'https://www.domain.tld'
baseVariants:
  -
    base: 'http://preview.domain.tld'
    condition: 'applicationContext == "Development/Server"'
  -
    base: 'http://www.domain.localhost'
    condition: 'applicationContext == "Development"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: '0'
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle:  DE
    hreflang: de
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: de
  -
    title: English
    enabled: true
    languageId: '2'
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: EN
    hreflang: en
    direction: ltr
    fallbackType: fallback
    fallbacks: '0'
    flag: en-us-gb
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=9' # uid = page UID from the BE page tree
  -
    errorCode: '503'
    errorHandler: Page
    errorContentSource: 't3://page?uid=10' # uid = page UID from the BE page tree
### Import default Robots.txt
imports:
  - { resource: "EXT:hh_theme_default/Configuration/Typo3/dummy_files/dummy_site/robots.yaml" }
  - { resource: "EXT:hh_theme_default/Configuration/Typo3/dummy_files/dummy_site/humans.yaml" }
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
  NewsPlugin:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/list/{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
      -
        routePath: '/tag/{tag_name}'
        _controller: 'News::list'
        _arguments:
          tag_name: overwriteDemand/tags
      -
        routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
      -
        routePath: '/archive/{year}/{month}'
        _controller: 'News::archive'
    defaultController: 'News::list'
    aspects:
      news_title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      tag-name:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_tag
        routeFieldName: slug
      year:
        type: StaticRangeMapper
        start: '2000'
        end: '2030'
      month:
        type: StaticValueMapper
        map:
          january: 1
          february: 2
          march: 3
          april: 4
          may: 5
          june: 6
          july: 7
          august: 8
          september: 9
          october: 10
          november: 11
          december: 12
        localeMap:
          - locale: 'de_.*'
            map:
                januar: 1
                februar: 2
                maerz: 3
                april: 4
                mai: 5
                juni: 6
                juli: 7
                august: 8
                september: 9
                oktober: 10
                november: 11
                dezember: 12
  AddressPlugin:
    type: Extbase
    extension: TtAddress
    plugin: ListView
    routes:
      - routePath: '/{address_slug}'
        _controller: 'Address::show'
        _arguments:
          address_slug: address
    aspects:
      address_slug:
        type: PersistedAliasMapper
        tableName: tt_address
        routeFieldName: slug
  IndexedSearchPlugin:
    type: Extbase
    namespace: 'tx_indexedsearch_pi2'
    routes:
      - { routePath: '/results', _controller: 'Search::search' }
      -
        routePath: '/results/{page}'
        _controller: 'Search::search'
        _arguments:
          page: '@widget_0/currentPage'
    defaultController: 'Search::search'
