name: Replace Strings

on:
  push:
    branches:
      - test
    paths-ignore:
      - 'README.md'

jobs:
  replace_strings:
    if: github.repository == 'hh_theme_default'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace strings
        run: |
          find . -type f -not -name "README.md" -print0 | while IFS= read -r -d $'\0' file; do
            sed -i "s/HauerHeinrich/{{EXTENSION_VENDOR}}/g" "$file"
            sed -i "s/HhThemeDefault/{{EXTENSION_NAMESPACE}}/g" "$file"
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Replace placeholder strings"
          push_options: '--force' # Optional: Kann nützlich sein, wenn der Branch nur für Tests ist
