name: Replace Strings

on:
  push:
    branches:
      - test-3
    paths-ignore:
      - 'README.md'

jobs:
  replace_strings:
    if: github.repository == 'hh_theme_default'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace strings
        run: |
          find . -type f \
            -not -path "./.git/*" \
            -not -path "./.github/*" \
            -not -name "README.md" \
            -print0 |
          while IFS= read -r -d $'\0' file; do
            awk '
            {
              line = $0

              ##### 1. Domain-Zeile zuerst rückgängig #####
              # test-theme-default.com → {{EXTENSION_DOMAIN_NAME}}.{{EXTENSION_DOMAIN_TLD}}
              gsub(/test-theme-default\.com/, "{{EXTENSION_DOMAIN_NAME}}.{{EXTENSION_DOMAIN_TLD}}", line)

              ##### 2. HauerHeinrich → nur wenn gefolgt von Namespace #####
              if (line ~ /HauerHeinrich\/(HhThemeDefault|hh-theme-default)/) {
                sub(/HauerHeinrich/, "{{EXTENSION_VENDOR}}", line)
              }

              ##### 3. EXT:hh_theme_default → {{EXTENSION_KEY}} #####
              gsub(/EXT:hh_theme_default/, "EXT:{{EXTENSION_KEY}}", line)

              ##### 4. standalone hh_theme_default → {{EXTENSION_KEY}} #####
              gsub(/\bhh_theme_default\b/, "{{EXTENSION_KEY}}", line)

              ##### 5. übrige hh_theme_default → {{EXTENSION_NAMESPACE_ES6}} #####
              gsub(/hh_theme_default/, "{{EXTENSION_NAMESPACE_ES6}}", line)

              ##### 6. HhThemeDefault → {{EXTENSION_NAMESPACE}} #####
              gsub(/HhThemeDefault/, "{{EXTENSION_NAMESPACE}}", line)

              ##### 7. hh-theme-default → {{EXTENSION_NAMESPACE_ES6}} #####
              gsub(/hh-theme-default/, "{{EXTENSION_NAMESPACE_ES6}}", line)

              ##### 8. test-theme-default → {{EXTENSION_DOMAIN_NAME}} (sofern noch vorhanden) #####
              gsub(/test-theme-default/, "{{EXTENSION_DOMAIN_NAME}}", line)

              ##### 9. com → {{EXTENSION_DOMAIN_TLD}}, nur wenn nach test-theme-default #####
              if (line ~ /test-theme-default\.com/) {
                sub(/com/, "{{EXTENSION_DOMAIN_TLD}}", line)
              }

              print line
            }' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
          done

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Replace placeholder strings"
          git push origin test-post-init
