name: Replace Strings

on:
  push:
    branches:
      - test-3
    paths-ignore:
      - 'README.md'

jobs:
  replace_strings:
    if: github.repository == 'Hauer-Heinrich/hh_theme_default'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace strings
        run: |
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -not -name "README.md" -print0 | while IFS= read -r -d $'\0' file; do
            sed -i "s|test-theme-default\.com|{{EXTENSION_DOMAIN_NAME}}.{{EXTENSION_DOMAIN_TLD}}|g" "$file"
            sed -i "s|HauerHeinrich/HhThemeDefault|{{EXTENSION_VENDOR}}/HhThemeDefault|g" "$file"
            sed -i "s|HauerHeinrich/hh-theme-default|{{EXTENSION_VENDOR}}/hh-theme-default|g" "$file"
            sed -i "s|EXT:hh_theme_default|EXT:{{EXTENSION_KEY}}|g" "$file"
            sed -i "s|'hh_theme_default'|{{EXTENSION_KEY}}|g" "$file"
            sed -i "s|hh-theme-default|{{EXTENSION_NAMESPACE_ES6}}|g" "$file"
            sed -i "s|test-theme-default|{{EXTENSION_DOMAIN_NAME}}|g" "$file"
            sed -i "s|{{EXTENSION_DOMAIN_NAME}}\.com|{{EXTENSION_DOMAIN_NAME}}.{{EXTENSION_DOMAIN_TLD}}|g" "$file"
          done

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Replace placeholder strings"
          git push origin test-3
